# Generated by Django 3.1.1 on 2021-01-23 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='NetModel',
            fields=[
                ('ModelKey', models.CharField(default='N/A', max_length=100, primary_key=True, serialize=False)),
                ('ModelType', models.CharField(default='N/A', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visual3D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='N/A', max_length=1000)),
                ('Xvalue', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('Yvalue', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('Zvalue', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('Attribute1', models.CharField(default='N/A', max_length=1000)),
                ('Attribute2', models.CharField(default='N/A', max_length=1000)),
                ('Attribute3', models.CharField(default='N/A', max_length=1000)),
                ('Attribute4', models.CharField(default='N/A', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Nodes_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DescKey', models.CharField(default='N/A', max_length=200)),
                ('EmpID', models.CharField(default='N/A', max_length=100)),
                ('Name', models.CharField(default='N/A', max_length=100)),
                ('Attribute1', models.CharField(default='N/A', max_length=200)),
                ('Attribute2', models.CharField(default='N/A', max_length=200)),
                ('Attribute3', models.CharField(default='N/A', max_length=200)),
                ('Node_Key', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='node_encrypt', to='Network.netmodel')),
            ],
        ),
        migrations.CreateModel(
            name='NodeDescriptor_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpID', models.CharField(default='N/A', max_length=100)),
                ('Grouping', models.IntegerField(default=0)),
                ('Centrality_Measure1', models.DecimalField(decimal_places=6, default=0, max_digits=50)),
                ('Centrality_Measure2', models.DecimalField(decimal_places=6, default=0, max_digits=50)),
                ('JDMeasure1', models.DecimalField(decimal_places=6, default=0, max_digits=50)),
                ('JDMeasure2', models.DecimalField(decimal_places=6, default=0, max_digits=50)),
                ('JDMeasure3', models.DecimalField(decimal_places=6, default=0, max_digits=50)),
                ('JDMeasure4', models.DecimalField(decimal_places=6, default=0, max_digits=50)),
                ('JDMeasure5', models.DecimalField(decimal_places=6, default=0, max_digits=50)),
                ('NDesc_Key', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='desc_encrypt', to='Network.nodes_model')),
            ],
        ),
        migrations.CreateModel(
            name='Links_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender', models.CharField(default='N/A', max_length=1000)),
                ('Recipient', models.CharField(default='N/A', max_length=1000)),
                ('Count', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Link_Key', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='link_encrypt', to='Network.netmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Inverted', models.BooleanField(default=False)),
                ('Email_Key', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, related_name='email_encrypt', to='Network.netmodel')),
                ('Recipient', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='email_recip', to='todo.employee')),
                ('Sender', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, related_name='email_send', to='todo.employee')),
            ],
        ),
    ]
