# Generated by Django 3.1.1 on 2021-03-19 23:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddress',
            fields=[
                ('AddressKey', models.CharField(max_length=100)),
                ('AddressName', models.CharField(default='N/A', max_length=200)),
                ('EmpID', models.CharField(default='N/A', max_length=20, primary_key=True, serialize=False)),
                ('CreateDate', models.DateField(verbose_name='Date')),
            ],
            managers=[
                ('Object', django.db.models.manager.Manager()),
            ],
        ),
    ]
