# Generated by Django 3.1.1 on 2021-07-31 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Network', '0002_emailaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='Time',
            field=models.TimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
