# Generated by Django 3.1.1 on 2021-01-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('JobCode', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('JobTitle', models.CharField(max_length=500)),
                ('Description', models.TextField()),
            ],
        ),
    ]
