# Generated by Django 3.1.1 on 2021-01-23 15:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpID', models.CharField(default='N/A', max_length=20, primary_key=True, serialize=False)),
                ('Name', models.CharField(default='N/A', max_length=200)),
                ('CreateDate', models.DateField(verbose_name='Date')),
                ('EmailAddress', models.CharField(default='N/A', max_length=100)),
            ],
            managers=[
                ('Object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('Report_Key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Report_Type', models.CharField(default='N/A', max_length=50)),
                ('Report_Date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TermDate', models.DateField(verbose_name='Date')),
                ('Name', models.CharField(default='N/A', max_length=120)),
                ('JobTitle', models.CharField(default='N/A', max_length=120)),
                ('Salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Department', models.CharField(default='N/A', max_length=120)),
                ('Location', models.CharField(default='N/A', max_length=120)),
                ('Report', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, related_name='encrypt3', to='todo.report')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ColumnName', models.CharField(default='N/A', max_length=120)),
                ('FieldType', models.CharField(default='N/A', max_length=30)),
                ('ReportName', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, related_name='encrypt4', to='todo.report')),
            ],
        ),
        migrations.CreateModel(
            name='Hires',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HireDate', models.DateField(verbose_name='Date')),
                ('Name', models.CharField(default='N/A', max_length=120)),
                ('JobTitle', models.CharField(default='N/A', max_length=120)),
                ('Salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Department', models.CharField(default='N/A', max_length=120)),
                ('Location', models.CharField(default='N/A', max_length=120)),
                ('EmpID', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, related_name='emp_hire', to='todo.employee')),
                ('Report', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, related_name='encrypt2', to='todo.report')),
            ],
        ),
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='N/A', max_length=120)),
                ('JobCode', models.CharField(default='N/A', max_length=120)),
                ('Salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Department', models.CharField(default='N/A', max_length=120)),
                ('Location', models.CharField(default='N/A', max_length=120)),
                ('EmpID', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, related_name='emp_demo', to='todo.employee')),
                ('Report', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, related_name='encrypt1', to='todo.report')),
            ],
        ),
    ]
