# Generated by Django 3.1.1 on 2021-01-23 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NLP', '0003_embedding_2'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModelKey', models.CharField(default='N/A', max_length=30)),
                ('Date', models.DateField(verbose_name='Date')),
                ('Salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Department', models.CharField(default='N/A', max_length=120)),
                ('Location', models.CharField(default='N/A', max_length=120)),
                ('ServiceLine', models.CharField(default='N/A', max_length=120)),
                ('EmpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encryptEmp', to='todo.employee')),
                ('JobCode', models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='jt_encrypt', to='NLP.jobtitles')),
            ],
        ),
    ]
