# Generated by Django 3.1.1 on 2021-01-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_employee_state_jobcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_state',
            name='JobCode',
            field=models.CharField(default='N/A', max_length=120),
        ),
    ]
