# Generated by Django 3.1.1 on 2021-01-24 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NLP', '0003_embedding_2'),
        ('todo', '0004_employee_state_jobcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_state',
            name='JobCodeModel',
            field=models.ManyToManyField(default='N/A', related_name='jobcode_enc', to='NLP.JobTitles'),
        ),
    ]
