# Generated by Django 3.1.1 on 2021-01-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_employee_state_jobcodemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_state',
            name='JobCodeModel',
        ),
        migrations.AddField(
            model_name='employee_state',
            name='Embedding1',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employee_state',
            name='Embedding2',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
